# Generated by Django 3.0.8 on 2020-11-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
