# Generated by Django 3.0.8 on 2020-11-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_demo_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='demo',
            name='insta_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
